# Generated by Django 3.2.5 on 2021-12-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv4_network',
            name='ip_address',
            field=models.CharField(default='192.161.0.0', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkinterfacecard',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.ipv4_network', to_field='ip_address'),
        ),
    ]
