# Generated by Django 3.2.5 on 2021-12-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0002_auto_20211207_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4_network',
            name='ip_address',
            field=models.CharField(default='165.224.36.151', max_length=1000, unique=True),
        ),
    ]
