# Generated by Django 3.2.5 on 2021-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0003_alter_ipv4_network_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4_network',
            name='ip_address',
            field=models.CharField(default='192.158.1.38', max_length=1000, unique=True),
        ),
    ]
