# Generated by Django 3.2.5 on 2021-12-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0004_alter_ipv4_network_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4_network',
            name='ip_address',
            field=models.CharField(default='2.88.109.39', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='networkinterfacecard',
            name='ip_address',
            field=models.ForeignKey(default='192.158.1.38', on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.ipv4_network', to_field='ip_address'),
        ),
    ]
