# Generated by Django 3.2.5 on 2021-12-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0006_auto_20211207_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterybackup',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack', unique=True),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack', unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack', unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack', unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack', unique=True),
        ),
    ]
