# Generated by Django 3.2.5 on 2021-12-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0007_auto_20211208_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterybackup',
            name='rack_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='rack_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
        migrations.AlterField(
            model_name='router',
            name='rack_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='rack_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.rack'),
        ),
    ]
