# Generated by Django 3.2.5 on 2021-12-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api_backend', '0008_auto_20211208_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfacecard',
            name='ip_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_api_backend.ipv4_network', to_field='ip_address'),
        ),
    ]
